---
- name: Start node-exporter play
  user: ubuntu
  hosts: web
  become: yes
  become_method: sudo
  become_user: root
  gather_facts: false
  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - ansible_host_key_checking: false
    - ansible_stdout_callback: yaml

  pre_tasks:
    - name: "wait 600 seconds for target connection to become reachable/usable."
      # Your code here
      ansible.builtin.pause:
        seconds: 10

    - name: "install python for Ansible."
      become: yes
      # Your code here
      apt:
        name: ["python3"]
        state: latest

  roles:
    - exporter