---
- name: Smoke test backend urls
  user: ubuntu
  hosts: web
  become: true
  become_method: sudo
  become_user: root  
  gather_facts: false
  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - ansible_host_key_checking: false
    - ansible_stdout_callback: yaml

  tasks:
    - name: "install python for Ansible."
      become: yes
      # Your code here
      apt:
        name: ["python3"]
        state: latest

    - name: Run smoke test url1
      become: yes
      shell:
        cmd: |
          dig +short myip.opendns.com @resolver1.opendns.com > url.txt
          URL="http://$(cat url.txt):9090"
          if curl "$URL/api/status" | grep "ok"
            then
                echo "Backend smoke test succeeded"
                exit 0
            else
                echo "Failed Backend smoke test"
                exit 1
            fi
