---
- name: Create directory
  become: yes
  file:
    path: /web
    state: directory
- name: Copy files to ec2 instance
  become: yes
  copy:
    src: ../../backend
    dest: /web
- name: Extract file and start server
  become: yes
  command: |
    cd /web/backend
    pm2 stop default
    pm2 start npm -- start