---
- name: Create directory
  become: yes
  file:
    path: ~/web
    state: directory

- name: Copy files to ec2 instance
  become: yes
  copy:
    src: ../../artifact.tar.gz
    dest: ~/web

- name: Extract file
  become: yes
  shell:
    cmd: |
      cd ~/web
      tar -xvzf artifact.tar.gz

- name: Start application
  become: yes
  shell:
    cmd: |
      cd ~/web
      npm install
      pm2 stop default
      pm2 start npm -- start