---
- name: Create directory
  file:
    path: /web
    state: directory
- name: Copy files to ec2 instance
  copy:
    src: artifact.tar.gz
    dest: /web
- name: Extract file and start server
  command: |
    cd /web
    tar -xvzf artifact.tar.gz
    cd backend
    npm install
    pm2 stop default
    pm2 start npm -- start