version: 2.1

executors:
  aws-exec-env:
    docker:
      - image: amazon/aws-cli
  node-exec-env:
    docker:
      - image: circleci/node:13.8.0

jobs:
  build-frontend:
    executor: node-exec-env
    steps:
      - checkout
      - run: 
          name: build/lint the frontend
          command: |
            cd frontend
            npm install
            npm run build

  build-backend:
    executor: node-exec-env
    steps:
      - checkout
      - run:
          name: build/compile the backend
          command: |
            cd backend
            npm install

workflows:
  default:
    jobs:
      - build-frontend
      - build-backend