version: 2.1

commands:
  build:
    description: build both fronend and backend
    steps:
      - run: |
          cd frontend
          npm install
          npm run build
  test:
    description: test both fronend and backend
    steps:
      - run: |
          cd frontend
          npm install
          npm run test

executors:
  aws-exec-env:
    docker:
      - image: amazon/aws-cli
  node-exec-env:
    docker:
      - image: circleci/node:13.8.0

jobs:
  build-frontend:
    executor: node-exec-env
    steps:
      - checkout
      - build
      - save_cache:
          paths: 
            - frontend/node_modules
          key: frontend-modules

    test-frontend:
      executor: node-exec-env
      steps:
        - checkout
        - restore_cache:
            keys:
              - frontend-modules
        - test

  build-backend:
    executor: node-exec-env
    steps:
      - checkout
      - build
      - save_cache:
          paths: 
            - backend/node_modules
          key: backend-modules

  test-backend:
    executor: node-exec-env
    steps:
      - checkout
      - restore_cache:
          keys:
            - backend-modules
      - test

workflows:
  default:
    jobs:
      - build-frontend
      - test-frontend:
          requires:
            - build-frontend
      - build-backend
      - test-backend:
          requires:
            - build-backend