---
- name: Copy alertmanager.yml
  become: yes
  copy:
    src: alertmanager.yml
    dest: /etc/prometheus/alertmanager.yml

- name: Copy alertmanager.service
  become: yes
  copy:
    src: alertmanager.service
    dest: /etc/systemd/system/alertmanager.service

- name: Copy prometheus.yml
  become: yes
  copy:
    src: prometheus.yml
    dest: /etc/prometheus/prometheus.yml
    backup: yes

- name: Install Alertmanager
  become: yes
  shell:
    cmd: |
      wget https://github.com/prometheus/alertmanager/releases/download/v0.21.0/alertmanager-0.21.0.linux-amd64.tar.gz
      tar xvfz alertmanager-0.21.0.linux-amd64.tar.gz
      cp alertmanager-0.21.0.linux-amd64/{alertmanager,amtool} /usr/local/bin
      mkdir /var/lib/alertmanager
      rm -rf alertmanager*
      chown prometheus:prometheus /usr/local/bin
      chown -R prometheus:prometheus /var/lib/alertmanager
      chown -R prometheus:prometheus /etc/prometheus

- name: Start Services
  become: yes
  shell:
    cmd: |
      systemctl daemon-reload
      systemctl enable alertmanager
      systemctl start alertmanager
      systemctl restart prometheus