---
- name: Copy files
  become: yes
  copy:
    src: node-exporter.service
    dest: /etc/systemd/system/node-exporter.service

- name: install node-exporter on ec2 instances
  become: yes
  shell:
    cmd: |
      useradd --no-create-home node_exporter
      wget https://github.com/prometheus/node_exporter/releases/download/v1.0.1/node_exporter-1.0.1.linux-amd64.tar.gz
      tar xzf node_exporter-1.0.1.linux-amd64.tar.gz
      cp node_exporter-1.0.1.linux-amd64/node_exporter /usr/local/bin/node_exporter
      chown node_exporter:node_exporter /usr/local/bin/node_exporter
      rm -rf node_exporter-1.0.1.linux-amd64.tar.gz node_exporter-1.0.1.linux-amd64

- name: Restart services
  become: yes
  shell:
    cmd: |
      systemctl daemon-reload
      systemctl enable node-exporter
      systemctl start node-exporter