global:
  scrape_interval: 1s
  evaluation_interval: 1s
  external_labels:
    monitor: 'prometheus'

rule_files:
 - /etc/prometheus/rules.yml

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - localhost:9093

scrape_configs:
  - job_name: 'node'
    ec2_sd_configs:
      - region: us-east-1
        access_key: AKIAUUPRS3W2XHJP4U2D
        secret_key: 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
        port: 9100

  - job_name: 'prometheus'
    static_configs:
      - targets: ['ec2-18-234-111-204.compute-1.amazonaws.com:9090']